name: 同步新闻30分到bsky
on:
  schedule:
    - cron: "*/3 4 * * *"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      - run: pip install -r requirements.txt
      - shell: bash
        env:
          atproto_username: ${{secrets.ATPROTO_USERNAME_XW30F}}
          atproto_password: ${{secrets.ATPROTO_PASSWORD_XW30F}}
        run: >
          python main.py --lm xw30f --service default --username "$atproto_username" --password "$atproto_password"
